// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PokerMind.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionRequestMember1_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "fold")]
        #pragma warning disable CS1591
        Fold,
        #pragma warning restore CS1591
        [EnumMember(Value = "check")]
        #pragma warning disable CS1591
        Check,
        #pragma warning restore CS1591
        [EnumMember(Value = "call")]
        #pragma warning disable CS1591
        Call,
        #pragma warning restore CS1591
        [EnumMember(Value = "all_in")]
        #pragma warning disable CS1591
        All_in,
        #pragma warning restore CS1591
    }
}
