// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PokerMind.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionRequestMember2_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "raise")]
        #pragma warning disable CS1591
        Raise,
        #pragma warning restore CS1591
    }
}
