// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PokerMind.Client.Models
{
    /// <summary>Card suit</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Card_suit
    {
        [EnumMember(Value = "clubs")]
        #pragma warning disable CS1591
        Clubs,
        #pragma warning restore CS1591
        [EnumMember(Value = "diamonds")]
        #pragma warning disable CS1591
        Diamonds,
        #pragma warning restore CS1591
        [EnumMember(Value = "hearts")]
        #pragma warning disable CS1591
        Hearts,
        #pragma warning restore CS1591
        [EnumMember(Value = "spades")]
        #pragma warning disable CS1591
        Spades,
        #pragma warning restore CS1591
    }
}
