// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PokerMind.Client.Models
{
    /// <summary>Current phase of the betting round</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Game_phase
    {
        [EnumMember(Value = "pre_flop")]
        #pragma warning disable CS1591
        Pre_flop,
        #pragma warning restore CS1591
        [EnumMember(Value = "flop")]
        #pragma warning disable CS1591
        Flop,
        #pragma warning restore CS1591
        [EnumMember(Value = "turn")]
        #pragma warning disable CS1591
        Turn,
        #pragma warning restore CS1591
        [EnumMember(Value = "river")]
        #pragma warning disable CS1591
        River,
        #pragma warning restore CS1591
        [EnumMember(Value = "game_finished")]
        #pragma warning disable CS1591
        Game_finished,
        #pragma warning restore CS1591
    }
}
