// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PokerMind.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Game : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current big blind amount</summary>
        public int? BigBlindAmount { get; set; }
        /// <summary>Cards on the table</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PokerMind.Client.Models.Card>? CommunityCards { get; set; }
#nullable restore
#else
        public List<global::PokerMind.Client.Models.Card> CommunityCards { get; set; }
#endif
        /// <summary>Player to act</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentPlayerId { get; set; }
#nullable restore
#else
        public string CurrentPlayerId { get; set; }
#endif
        /// <summary>Number of hands currently played for this table</summary>
        public int? HandsPlayed { get; set; }
        /// <summary>Current bet to match</summary>
        public int? HighestRaise { get; set; }
        /// <summary>Game ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>List of other players in the game</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PokerMind.Client.Models.Player>? OtherPlayers { get; set; }
#nullable restore
#else
        public List<global::PokerMind.Client.Models.Player> OtherPlayers { get; set; }
#endif
        /// <summary>Current phase of the betting round</summary>
        public global::PokerMind.Client.Models.Game_phase? Phase { get; set; }
        /// <summary>The player property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PokerMind.Client.Models.Game_player? Player { get; set; }
#nullable restore
#else
        public global::PokerMind.Client.Models.Game_player Player { get; set; }
#endif
        /// <summary>Current size of the pot</summary>
        public int? Pot { get; set; }
        /// <summary>The lowest possible raise to perform</summary>
        public int? RaiseAmount { get; set; }
        /// <summary>Small blind player</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmallBlindId { get; set; }
#nullable restore
#else
        public string SmallBlindId { get; set; }
#endif
        /// <summary>The winner of the table</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Winner { get; set; }
#nullable restore
#else
        public string Winner { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PokerMind.Client.Models.Game"/> and sets the default values.
        /// </summary>
        public Game()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PokerMind.Client.Models.Game"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PokerMind.Client.Models.Game CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PokerMind.Client.Models.Game();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "big_blind_amount", n => { BigBlindAmount = n.GetIntValue(); } },
                { "community_cards", n => { CommunityCards = n.GetCollectionOfObjectValues<global::PokerMind.Client.Models.Card>(global::PokerMind.Client.Models.Card.CreateFromDiscriminatorValue)?.AsList(); } },
                { "current_player_id", n => { CurrentPlayerId = n.GetStringValue(); } },
                { "hands_played", n => { HandsPlayed = n.GetIntValue(); } },
                { "highest_raise", n => { HighestRaise = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "other_players", n => { OtherPlayers = n.GetCollectionOfObjectValues<global::PokerMind.Client.Models.Player>(global::PokerMind.Client.Models.Player.CreateFromDiscriminatorValue)?.AsList(); } },
                { "phase", n => { Phase = n.GetEnumValue<global::PokerMind.Client.Models.Game_phase>(); } },
                { "player", n => { Player = n.GetObjectValue<global::PokerMind.Client.Models.Game_player>(global::PokerMind.Client.Models.Game_player.CreateFromDiscriminatorValue); } },
                { "pot", n => { Pot = n.GetIntValue(); } },
                { "raise_amount", n => { RaiseAmount = n.GetIntValue(); } },
                { "small_blind_id", n => { SmallBlindId = n.GetStringValue(); } },
                { "winner", n => { Winner = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("big_blind_amount", BigBlindAmount);
            writer.WriteCollectionOfObjectValues<global::PokerMind.Client.Models.Card>("community_cards", CommunityCards);
            writer.WriteStringValue("current_player_id", CurrentPlayerId);
            writer.WriteIntValue("hands_played", HandsPlayed);
            writer.WriteIntValue("highest_raise", HighestRaise);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::PokerMind.Client.Models.Player>("other_players", OtherPlayers);
            writer.WriteEnumValue<global::PokerMind.Client.Models.Game_phase>("phase", Phase);
            writer.WriteObjectValue<global::PokerMind.Client.Models.Game_player>("player", Player);
            writer.WriteIntValue("pot", Pot);
            writer.WriteIntValue("raise_amount", RaiseAmount);
            writer.WriteStringValue("small_blind_id", SmallBlindId);
            writer.WriteStringValue("winner", Winner);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
