// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PokerMind.Client.Models
{
    /// <summary>Current state of the player</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Player_state
    {
        [EnumMember(Value = "active_in_hand")]
        #pragma warning disable CS1591
        Active_in_hand,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive_in_hand")]
        #pragma warning disable CS1591
        Inactive_in_hand,
        #pragma warning restore CS1591
        [EnumMember(Value = "all_in")]
        #pragma warning disable CS1591
        All_in,
        #pragma warning restore CS1591
        [EnumMember(Value = "out_of_chips")]
        #pragma warning disable CS1591
        Out_of_chips,
        #pragma warning restore CS1591
    }
}
