// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PokerMind.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Player : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current bet this betting round</summary>
        public int? CurrentBet { get; set; }
        /// <summary>Whether the player has acted in this betting round</summary>
        public bool? HasActed { get; set; }
        /// <summary>Player ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Remaining chips</summary>
        public int? RemainingChips { get; set; }
        /// <summary>Current state of the player</summary>
        public global::PokerMind.Client.Models.Player_state? State { get; set; }
        /// <summary>Total contribution of chips this betting round</summary>
        public int? TotalContributed { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PokerMind.Client.Models.Player"/> and sets the default values.
        /// </summary>
        public Player()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PokerMind.Client.Models.Player"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PokerMind.Client.Models.Player CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PokerMind.Client.Models.Player();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_bet", n => { CurrentBet = n.GetIntValue(); } },
                { "has_acted", n => { HasActed = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "remaining_chips", n => { RemainingChips = n.GetIntValue(); } },
                { "state", n => { State = n.GetEnumValue<global::PokerMind.Client.Models.Player_state>(); } },
                { "total_contributed", n => { TotalContributed = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("current_bet", CurrentBet);
            writer.WriteBoolValue("has_acted", HasActed);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("remaining_chips", RemainingChips);
            writer.WriteEnumValue<global::PokerMind.Client.Models.Player_state>("state", State);
            writer.WriteIntValue("total_contributed", TotalContributed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
