// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PokerMind.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PokerMind.Client.Api.Next_games
{
    /// <summary>
    /// Builds and executes requests for operations under \api\next_games
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Next_gamesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Next_gamesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/next_games{?player_id*,suite_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Next_gamesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/next_games{?player_id*,suite_id*}", rawUrl)
        {
        }
        /// <summary>
        /// List upcoming games
        /// </summary>
        /// <returns>A <see cref="global::PokerMind.Client.Models.GameResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PokerMind.Client.Models.BadRequest">When receiving a 400 status code</exception>
        /// <exception cref="global::PokerMind.Client.Models.NotFound">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PokerMind.Client.Models.GameResponse?> GetAsync(Action<RequestConfiguration<global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder.Next_gamesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PokerMind.Client.Models.GameResponse> GetAsync(Action<RequestConfiguration<global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder.Next_gamesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PokerMind.Client.Models.BadRequest.CreateFromDiscriminatorValue },
                { "404", global::PokerMind.Client.Models.NotFound.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::PokerMind.Client.Models.GameResponse>(requestInfo, global::PokerMind.Client.Models.GameResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List upcoming games
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder.Next_gamesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder.Next_gamesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List upcoming games
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Next_gamesRequestBuilderGetQueryParameters 
        {
            /// <summary>Your ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("player_id")]
            public string? PlayerId { get; set; }
#nullable restore
#else
            [QueryParameter("player_id")]
            public string PlayerId { get; set; }
#endif
            /// <summary>Suite ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("suite_id")]
            public string? SuiteId { get; set; }
#nullable restore
#else
            [QueryParameter("suite_id")]
            public string SuiteId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Next_gamesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder.Next_gamesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
