// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PokerMind.Client.Api.ActionNamespace;
using PokerMind.Client.Api.Close_suite;
using PokerMind.Client.Api.Next_games;
using PokerMind.Client.Api.Start_suite;
using PokerMind.Client.Api.Suites;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PokerMind.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The action property</summary>
        public global::PokerMind.Client.Api.ActionNamespace.ActionRequestBuilder Action
        {
            get => new global::PokerMind.Client.Api.ActionNamespace.ActionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The close_suite property</summary>
        public global::PokerMind.Client.Api.Close_suite.Close_suiteRequestBuilder Close_suite
        {
            get => new global::PokerMind.Client.Api.Close_suite.Close_suiteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The next_games property</summary>
        public global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder Next_games
        {
            get => new global::PokerMind.Client.Api.Next_games.Next_gamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start_suite property</summary>
        public global::PokerMind.Client.Api.Start_suite.Start_suiteRequestBuilder Start_suite
        {
            get => new global::PokerMind.Client.Api.Start_suite.Start_suiteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The suites property</summary>
        public global::PokerMind.Client.Api.Suites.SuitesRequestBuilder Suites
        {
            get => new global::PokerMind.Client.Api.Suites.SuitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PokerMind.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PokerMind.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
